---
deployment:
  tasks:
    - name: Deploy from Sustainboostsecurecode to public_html
      command: |
        export REPO_PATH=/home/sustainbci/repositories/Sustainboostsecurecode
        export DEPLOY_PATH=/home/sustainbci/public_html

        # Remove existing files in public_html
        /bin/rm -rf $DEPLOY_PATH/*

        # Copy new files from the repository
        /bin/cp -r $REPO_PATH/* $DEPLOY_PATH/
